[workspace]
members = [ "boids",
    "web-server",
    "wgol",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["FUJINAKA Fumiya <uzuna.kf@gmail.com>"]
repository = "https://github.com/uzuna/wasm-tutorial"
rust-version = "1.79"
