[package]
name = "webgl2"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
vertex = ["web-sys/WebGlBuffer", "web-sys/WebGlUniformLocation"]
context = ["web-sys/HtmlCanvasElement"]

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
js-sys.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    "WebGl2RenderingContext",
    "WebGlProgram",
    "WebGlShader",
    "WebGlVertexArrayObject",
]

[dev-dependencies]
wasm-bindgen-test.workspace = true

[dev-dependencies.web-sys]
workspace = true
features = [
    'Element',
    'HtmlElement',
    'Node',
    "Document",
    "HtmlCanvasElement",
    "Window",
]
