[package]
name = "sim-view"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
wasm-utils.workspace = true
webgl2 = { workspace = true, features = ["vertex", "context", "viewport", "shader"] }

[dependencies.web-sys]
workspace = true
features = []
