[package]
name = "lqr"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nalgebra.workspace = true
ndarray = "0.16.1"
ndarray-linalg = "0.16.0"
